import type { Metadata } from "next";
import Image from "next/image";
// import { Inter } from "next/font/google";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
    title: "FCA",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head />
            <body
                className={cn(
                    "min-h-screen bg-background font-sans antialiased",
                    fontSans.variable
                )}
            >
                <div className="flex justify-center my-8">
                    <Image
                        src="/FCA Circle Logo Color.png"
                        alt="logo"
                        width={228}
                        height={228}
                    />
                </div>
                {children}
            </body>
        </html>
    );
}
